name: Generate Snake with GIF

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate Snake .gif dark animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-snake-ocean.gif
          color_snake: "#FACC15" # amarillo solar
          color_dots: "#0f172a,#1e293b,#334155,#64748b,#cbd5e1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List generated files
        run: ls -lh dist/

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




