name: Generate Snake SVGs (Light + Dark)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate SVGs (Light & Dark)
        uses: Platane/snk@v3
        with:
          github_user_name: PedroCere
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            

      - name: Show dist contents
        run: ls -l dist/

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
